#spring.application.name=HelloWorld
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/curd
    username: postgres
    password: dbadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  address: 0.0.0.0